name: Transparency Expert
favicon: null
layout_spectrum: 1
typography_spectrum: 0.35851
title: Transparency Expert
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5
  lightness: 0.38582166051492095
  saturation: 0.45171513478271663
  rhythmicContrast: 0.36410717316903174
purpose: []
